In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [3]:
a.shape

(2, 3)

In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
a[0]

np.int64(1)

In [5]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [7]:
a[:3]

array([10,  2,  3])

In [8]:
b = a[3:]
b

array([4, 5, 6])

In [9]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [11]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
a[1, 3]

np.int64(8)

In [15]:
a.ndim

2

In [17]:
a.shape

(3, 4)

In [19]:
len(a.shape) == a.ndim

True

In [21]:
a.size

12

In [23]:
import math

In [26]:
a.size == math.prod(a.shape)

True

In [25]:
a.dtype

dtype('int64')

In [27]:
np.zeros(2)

array([0., 0.])

In [28]:
np.ones(2)

array([1., 1.])

In [30]:
np.empty(2) 

array([1., 1.])

In [31]:
np.arange(4)

array([0, 1, 2, 3])

In [32]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [33]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [35]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [36]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [39]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [41]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [46]:
array_example.ndim

3

In [47]:
array_example.size

24

In [48]:
array_example.shape

(3, 2, 4)

In [49]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [50]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [53]:
np.reshape(a, shape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [54]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [55]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [56]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [57]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [58]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [59]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [60]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [62]:
import numpy as np

In [63]:
data = np.array([1, 2, 3])

data[1]

np.int64(2)

In [64]:
data[0:2]

array([1, 2])

In [65]:
data[1:]

array([2, 3])

In [66]:
data[-2:]

array([2, 3])

In [67]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [70]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
a < 5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [68]:
print(a[a < 5])

[1 2 3 4]


In [69]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [72]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [73]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [74]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [75]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [76]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [77]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [78]:
print(a[b])

[1 2 3 4]


In [79]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [81]:
 a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [83]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [84]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [85]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [86]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [87]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [88]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [93]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [94]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [95]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [96]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [98]:
b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [99]:
import numpy as np

In [100]:
data = np.array([1, 2])

In [101]:
ones = np.ones(2, dtype=int)

In [102]:
data + ones

array([2, 3])

In [103]:
data - ones

array([0, 1])

In [104]:
data * data

array([1, 4])

In [105]:
data / data

array([1., 1.])

In [106]:
a = np.array([1, 2, 3, 4])

In [107]:
a.sum()

np.int64(10)

In [108]:
b = np.array([[1, 1], [2, 2]])

In [110]:
b.sum(axis=0)

array([3, 3])

In [111]:
b.sum(axis=1)

array([2, 4])

In [112]:
data = np.array([1.0, 2.0])

In [114]:
data * 1.6

array([1.6, 3.2])

In [125]:
import numpy as np

In [126]:
data = np.array([1, 2, 3])

In [127]:
data.max()

np.int64(3)

In [128]:
data.min()

np.int64(1)

In [129]:
data.sum()

np.int64(6)

In [130]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [131]:
a.sum()

np.float64(4.8595784)

In [132]:
a.min()

np.float64(0.05093587)

In [133]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [134]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [135]:
data[0, 1]

np.int64(2)

In [136]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [137]:
data[0:2, 0]

array([1, 3])

In [138]:
data.max()

np.int64(6)

In [139]:
data.min()

np.int64(1)

In [140]:
data.sum()

np.int64(21)

In [141]:
data = np.array([[1, 2], [5, 3], [4, 6]])

In [142]:
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [143]:
data.max(axis=0)

array([5, 6])

In [144]:
data.max(axis=1)

array([2, 5, 6])

In [145]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [146]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [147]:
np.ones(3)

array([1., 1., 1.])

In [148]:
np.zeros(3)

array([0., 0., 0.])

In [150]:
rng = np.random.default_rng()  
rng.random(3) 

array([0.42485565, 0.92939571, 0.76265087])

In [151]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [152]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [153]:
rng.random((3, 2)) 

array([[0.9233062 , 0.53488273],
       [0.75361427, 0.42186137],
       [0.43066055, 0.75258153]])

In [155]:
rng.integers(5, size=(2, 4)) 

array([[1, 2, 4, 0],
       [0, 4, 0, 0]])

In [156]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [157]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [158]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [159]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [160]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [161]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [162]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [163]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [164]:
print(indices)

[0 1 2]


In [165]:
print(occurrence_count)

[2 1 1]


In [167]:
import numpy as np

In [169]:
data = np.array([1, 2, 3, 4, 5,6])

In [170]:
data

array([1, 2, 3, 4, 5, 6])

In [171]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [172]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [173]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [174]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [175]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [176]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [177]:
reversed_arr = np.flip(arr)

In [178]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [179]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [180]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [181]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [182]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [183]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [184]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [185]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [186]:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [187]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [188]:
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [189]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
